import streamlit as st
import requests
import io
from PIL import Image
import random

# --- 1. CONFIG & AUTH ---
API_URL = "https://api-inference.huggingface.co/models/stabilityai/sdxl-turbo"
headers = {"Authorization": f"Bearer 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"}

st.set_page_config(page_title="Penguin AI", page_icon="🐧", layout="centered")

# --- 2. SESSION STATE ---
if "p_val" not in st.session_state: st.session_state.p_val = ""
if "generated_image" not in st.session_state: st.session_state.generated_image = None

# --- 3. UI & GLOW CSS (LOCKED UX) ---
st.markdown("""
    <style>
    .stApp { background-color: #0E1117; color: white; }
    
    /* Input field */
    .stTextInput>div>div>input {
        background-color: #1A1C23; color: white; border: 1px solid #333; border-radius: 10px;
    }

    /* Green Glow Button */
    .stButton>button { 
        border-radius: 12px; border: 1px solid #4CAF50; background-color: #1A1C23;
        color: white; font-weight: bold; width: 100%; padding: 15px;
        box-shadow: 0 0 5px rgba(76, 175, 80, 0.2); transition: 0.3s;
    }
    .stButton>button:hover { 
        border-color: #00E676; color: #00E676; 
        box-shadow: 0 0 20px rgba(0, 230, 118, 0.5); 
    }

    /* Download Button Specific Styling */
    div.stDownloadButton > button {
        background: linear-gradient(90deg, #4CAF50, #00E676) !important;
        color: black !important;
        border: none !important;
        font-size: 18px !important;
        height: 50px !important;
    }

    .footer { position: fixed; bottom: 0; left: 0; width: 100%; text-align: center; padding: 10px; background: #0E1117; border-top: 1px solid #2e2e2e; color: gray; }
    </style>
    """, unsafe_allow_html=True)

def query(payload):
    response = requests.post(API_URL, headers=headers, json=payload, timeout=25)
    if response.status_code != 200:
        return None
    return response.content

st.title("🐧 Penguin AI")
st.write("<p style='text-align: center; color: #88C0D0;'>Turbo Engine • One-Click Save</p>", unsafe_allow_html=True)

# --- 4. INPUT AREA ---
col1, col2 = st.columns([4, 1])
with col1:
    user_input = st.text_input("Enter your wallpaper prompt:", value=st.session_state.p_val, placeholder="E.g. Cyberpunk street, 8k, neon...")
with col2:
    st.write("<br>", unsafe_allow_html=True)
    if st.button("✨"):
        ideas = ["Neon Samurai", "Ice Dragon", "Viking Warrior", "Space Explorer"]
        st.session_state.p_val = random.choice(ideas)
        st.rerun()

# --- 5. GENERATION LOGIC ---
if st.button("Generate Masterpiece 🚀", use_container_width=True):
    if user_input:
        st.session_state.p_val = user_input
        with st.status("Generating Art...", expanded=True) as status:
            image_bytes = query({"inputs": f"{user_input}, high quality, cinematic"})
            
            if image_bytes:
                try:
                    image = Image.open(io.BytesIO(image_bytes))
                    st.session_state.generated_image = image
                    status.update(label="Success!", state="complete", expanded=False)
                except:
                    st.error("Engine busy. Try again in 5 seconds.")
            else:
                st.error("Server is waking up. Click Generate again.")
    else:
        st.warning("Kuch likho toh sahi!")

# --- 6. DISPLAY & DOWNLOAD (The Final Goal) ---
if st.session_state.generated_image:
    st.markdown("---")
    # Display Image
    st.image(st.session_state.generated_image, use_container_width=True, caption="Generated by Penguin AI")
    
    # Prepare Image for Download
    buf = io.BytesIO()
    st.session_state.generated_image.save(buf, format="PNG")
    byte_im = buf.getvalue()
    
    # THE DOWNLOAD BUTTON
    st.download_button(
        label="💾 SAVE & DOWNLOAD WALLPAPER",
        data=byte_im,
        file_name="penguin_masterpiece.png",
        mime="image/png",
        use_container_width=True
    )
    st.success("Image ready! Click the button above to save.")

st.markdown('<div class="footer">Built by Agni-India • 2026</div>', unsafe_allow_html=True)
