import streamlit as st
import random
import urllib.parse

# --- 1. PAGE CONFIG ---
st.set_page_config(page_title="Penguin AI", page_icon="🐧", layout="centered")

# --- 2. SESSION STATE (Buttons fix karne ke liye) ---
if "final_prompt" not in st.session_state:
    st.session_state.final_prompt = ""
if "history" not in st.session_state:
    st.session_state.history = []

# --- 3. PREMIUM DARK CSS ---
st.markdown("""
    <style>
    .stApp { background-color: #0E1117; color: white; }
    .stButton>button { 
        border-radius: 10px; border: 1px solid #4CAF50; background-color: #1A1C23;
        color: white; font-weight: bold; width: 100%; height: 3.5em;
    }
    .stButton>button:hover { border-color: #00E676; color: #00E676; shadow: 0 0 10px #00E676; }
    .footer { position: fixed; bottom: 0; left: 0; width: 100%; text-align: center; padding: 10px; background: #0E1117; border-top: 1px solid #2e2e2e; color: gray; }
    input { background-color: #1A1C23 !important; color: white !important; }
    </style>
    """, unsafe_allow_html=True)

st.title("🐧 Penguin AI")

# --- 4. SURPRISE ME LOGIC ---
surprise_options = [
    "A cyberpunk penguin with neon wings in a rainy city, 8k",
    "A majestic lion king made of stardust and galaxies",
    "Futuristic sports car driving on a rainbow bridge",
    "A cute baby dragon sleeping on a pile of gold coins"
]

# UI Layout
col1, col2 = st.columns([4, 1])

with col1:
    # Text input hamesha session_state se juda rahega
    user_input = st.text_input("What's in your mind?", value=st.session_state.final_prompt)

with col2:
    st.write("<br>", unsafe_allow_html=True)
    if st.button("Surprise ✨"):
        st.session_state.final_prompt = random.choice(surprise_options)
        st.rerun()

# --- 5. GENERATE LOGIC ---
if st.button("Generate Masterpiece 🚀", use_container_width=True):
    if user_input:
        st.session_state.final_prompt = user_input # Input save karo
        with st.spinner("Wait... Penguin is painting 🎨"):
            seed = random.randint(1, 999999)
            encoded_prompt = urllib.parse.quote(user_input)
            
            # Using a very stable URL format
            image_url = f"https://pollinations.ai/p/{encoded_prompt}?seed={seed}&width=1024&height=1024&model=flux&nologo=true"
            
            # Displaying the image
            st.image(image_url, caption="Generated by Penguin AI", use_container_width=True)
            
            # Save and Download Buttons
            st.success("Masterpiece Ready!")
            st.markdown(f'''
                <a href="{image_url}" target="_blank" download="PenguinAI_Art.png">
                    <button style="width:100%; background-color:#4CAF50; color:white; padding:12px; border-radius:10px; border:none; cursor:pointer; font-weight:bold;">
                        Download High-Res Image 📥
                    </button>
                </a>
            ''', unsafe_allow_html=True)
            
            # Add to History
            if {"prompt": user_input, "url": image_url} not in st.session_state.history:
                st.session_state.history.insert(0, {"prompt": user_input, "url": image_url})
    else:
        st.warning("Pehle kuch likho toh sahi, bhai!")

# --- 6. HISTORY GALLERY ---
if st.session_state.history:
    st.write("---")
    st.subheader("🕒 Recent Creations")
    h_cols = st.columns(3)
    for idx, item in enumerate(st.session_state.history[:6]):
        with h_cols[idx % 3]:
            st.image(item["url"], use_container_width=True)

st.markdown('<div class="footer">Built with Passion by Agni-India</div>', unsafe_allow_html=True)
